"""add poc_user table

Revision ID: 3b182d057cb9
Revises: 20260413_0004
Create Date: 2026-05-01 15:13:45.424181
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = '3b182d057cb9'
down_revision = '20260413_0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poc_user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_poc_user')),
    sa.UniqueConstraint('email', name=op.f('uq_poc_user_email'))
    )
    op.drop_index(op.f('idx_data_raw_record_generation_sample_id'), table_name='data_raw_record')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_data_raw_record_generation_sample_id'), 'data_raw_record', ['generation_sample_id'], unique=False)
    op.drop_table('poc_user')
    # ### end Alembic commands ###